// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package server

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "vivian/pkg/server/Add",
		Iface: reflect.TypeOf((*Add)(nil)).Elem(),
		Impl:  reflect.TypeOf(add{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return add_local_stub{impl: impl.(Add), tracer: tracer, databaseAddAccountMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/Add", Method: "DatabaseAddAccount", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return add_client_stub{stub: stub, databaseAddAccountMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/Add", Method: "DatabaseAddAccount", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return add_server_stub{impl: impl.(Add), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return add_reflect_stub{caller: caller}
		},
		RefData: "",
	})
	codegen.Register(codegen.Registration{
		Name:  "vivian/pkg/server/Echo",
		Iface: reflect.TypeOf((*Echo)(nil)).Elem(),
		Impl:  reflect.TypeOf(echo{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return echo_local_stub{impl: impl.(Echo), tracer: tracer, echoResponseMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/Echo", Method: "EchoResponse", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return echo_client_stub{stub: stub, echoResponseMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/Echo", Method: "EchoResponse", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return echo_server_stub{impl: impl.(Echo), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return echo_reflect_stub{caller: caller}
		},
		RefData: "",
	})
	codegen.Register(codegen.Registration{
		Name:  "vivian/pkg/server/Login",
		Iface: reflect.TypeOf((*Login)(nil)).Elem(),
		Impl:  reflect.TypeOf(login{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return login_local_stub{impl: impl.(Login), tracer: tracer, loginMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/Login", Method: "Login", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return login_client_stub{stub: stub, loginMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/Login", Method: "Login", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return login_server_stub{impl: impl.(Login), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return login_reflect_stub{caller: caller}
		},
		RefData: "",
	})
	codegen.Register(codegen.Registration{
		Name:      "github.com/ServiceWeaver/weaver/Main",
		Iface:     reflect.TypeOf((*weaver.Main)(nil)).Elem(),
		Impl:      reflect.TypeOf(App{}),
		Listeners: []string{"vivian"},
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return main_local_stub{impl: impl.(weaver.Main), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any { return main_client_stub{stub: stub} },
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return main_server_stub{impl: impl.(weaver.Main), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return main_reflect_stub{caller: caller}
		},
		RefData: "⟦d2edcb68:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→vivian/pkg/server/Echo⟧\n⟦e5803fa6:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→vivian/pkg/server/Add⟧\n⟦8728d12f:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→vivian/pkg/server/Login⟧\n⟦2f15269b:wEaVeRlIsTeNeRs:github.com/ServiceWeaver/weaver/Main→vivian⟧\n",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[Add] = (*add)(nil)
var _ weaver.InstanceOf[Echo] = (*echo)(nil)
var _ weaver.InstanceOf[Login] = (*login)(nil)
var _ weaver.InstanceOf[weaver.Main] = (*App)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*add)(nil)
var _ weaver.Unrouted = (*echo)(nil)
var _ weaver.Unrouted = (*login)(nil)
var _ weaver.Unrouted = (*App)(nil)

// Local stub implementations.

type add_local_stub struct {
	impl                      Add
	tracer                    trace.Tracer
	databaseAddAccountMetrics *codegen.MethodMetrics
}

// Check that add_local_stub implements the Add interface.
var _ Add = (*add_local_stub)(nil)

func (s add_local_stub) DatabaseAddAccount(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	begin := s.databaseAddAccountMetrics.Begin()
	defer func() { s.databaseAddAccountMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "server.Add.DatabaseAddAccount", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.DatabaseAddAccount(ctx, a0)
}

type echo_local_stub struct {
	impl                Echo
	tracer              trace.Tracer
	echoResponseMetrics *codegen.MethodMetrics
}

// Check that echo_local_stub implements the Echo interface.
var _ Echo = (*echo_local_stub)(nil)

func (s echo_local_stub) EchoResponse(ctx context.Context, a0 string) (err error) {
	// Update metrics.
	begin := s.echoResponseMetrics.Begin()
	defer func() { s.echoResponseMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "server.Echo.EchoResponse", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.EchoResponse(ctx, a0)
}

type login_local_stub struct {
	impl         Login
	tracer       trace.Tracer
	loginMetrics *codegen.MethodMetrics
}

// Check that login_local_stub implements the Login interface.
var _ Login = (*login_local_stub)(nil)

func (s login_local_stub) Login(ctx context.Context, a0 string, a1 string) (r0 bool, err error) {
	// Update metrics.
	begin := s.loginMetrics.Begin()
	defer func() { s.loginMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "server.Login.Login", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Login(ctx, a0, a1)
}

type main_local_stub struct {
	impl   weaver.Main
	tracer trace.Tracer
}

// Check that main_local_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_local_stub)(nil)

// Client stub implementations.

type add_client_stub struct {
	stub                      codegen.Stub
	databaseAddAccountMetrics *codegen.MethodMetrics
}

// Check that add_client_stub implements the Add interface.
var _ Add = (*add_client_stub)(nil)

func (s add_client_stub) DatabaseAddAccount(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.databaseAddAccountMetrics.Begin()
	defer func() { s.databaseAddAccountMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "server.Add.DatabaseAddAccount", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.String()
	err = dec.Error()
	return
}

type echo_client_stub struct {
	stub                codegen.Stub
	echoResponseMetrics *codegen.MethodMetrics
}

// Check that echo_client_stub implements the Echo interface.
var _ Echo = (*echo_client_stub)(nil)

func (s echo_client_stub) EchoResponse(ctx context.Context, a0 string) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.echoResponseMetrics.Begin()
	defer func() { s.echoResponseMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "server.Echo.EchoResponse", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

type login_client_stub struct {
	stub         codegen.Stub
	loginMetrics *codegen.MethodMetrics
}

// Check that login_client_stub implements the Login interface.
var _ Login = (*login_client_stub)(nil)

func (s login_client_stub) Login(ctx context.Context, a0 string, a1 string) (r0 bool, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.loginMetrics.Begin()
	defer func() { s.loginMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "server.Login.Login", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	size += (4 + len(a1))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	enc.String(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.Bool()
	err = dec.Error()
	return
}

type main_client_stub struct {
	stub codegen.Stub
}

// Check that main_client_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_client_stub)(nil)

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.22.0 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type add_server_stub struct {
	impl    Add
	addLoad func(key uint64, load float64)
}

// Check that add_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*add_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s add_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "DatabaseAddAccount":
		return s.databaseAddAccount
	default:
		return nil
	}
}

func (s add_server_stub) databaseAddAccount(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.DatabaseAddAccount(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.String(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

type echo_server_stub struct {
	impl    Echo
	addLoad func(key uint64, load float64)
}

// Check that echo_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*echo_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s echo_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "EchoResponse":
		return s.echoResponse
	default:
		return nil
	}
}

func (s echo_server_stub) echoResponse(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.EchoResponse(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

type login_server_stub struct {
	impl    Login
	addLoad func(key uint64, load float64)
}

// Check that login_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*login_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s login_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Login":
		return s.login
	default:
		return nil
	}
}

func (s login_server_stub) login(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()
	var a1 string
	a1 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Login(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Bool(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

type main_server_stub struct {
	impl    weaver.Main
	addLoad func(key uint64, load float64)
}

// Check that main_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*main_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s main_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	default:
		return nil
	}
}

// Reflect stub implementations.

type add_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that add_reflect_stub implements the Add interface.
var _ Add = (*add_reflect_stub)(nil)

func (s add_reflect_stub) DatabaseAddAccount(ctx context.Context, a0 string) (r0 string, err error) {
	err = s.caller("DatabaseAddAccount", ctx, []any{a0}, []any{&r0})
	return
}

type echo_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that echo_reflect_stub implements the Echo interface.
var _ Echo = (*echo_reflect_stub)(nil)

func (s echo_reflect_stub) EchoResponse(ctx context.Context, a0 string) (err error) {
	err = s.caller("EchoResponse", ctx, []any{a0}, []any{})
	return
}

type login_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that login_reflect_stub implements the Login interface.
var _ Login = (*login_reflect_stub)(nil)

func (s login_reflect_stub) Login(ctx context.Context, a0 string, a1 string) (r0 bool, err error) {
	err = s.caller("Login", ctx, []any{a0, a1}, []any{&r0})
	return
}

type main_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that main_reflect_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_reflect_stub)(nil)

