// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package server

import (
	"context"
	"errors"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:      "github.com/ServiceWeaver/weaver/Main",
		Iface:     reflect.TypeOf((*weaver.Main)(nil)).Elem(),
		Impl:      reflect.TypeOf(Server{}),
		Listeners: []string{"vivian"},
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return main_local_stub{impl: impl.(weaver.Main), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any { return main_client_stub{stub: stub} },
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return main_server_stub{impl: impl.(weaver.Main), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return main_reflect_stub{caller: caller}
		},
		RefData: "⟦ecef972a:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→vivian/pkg/server/handleInterface⟧\n⟦2f15269b:wEaVeRlIsTeNeRs:github.com/ServiceWeaver/weaver/Main→vivian⟧\n",
	})
	codegen.Register(codegen.Registration{
		Name:  "vivian/pkg/server/handleInterface",
		Iface: reflect.TypeOf((*handleInterface)(nil)).Elem(),
		Impl:  reflect.TypeOf(serverControls{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return handleInterface_local_stub{impl: impl.(handleInterface), tracer: tracer, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/handleInterface", Method: "Add", Remote: false}), innerEchoMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/handleInterface", Method: "InnerEcho", Remote: false}), pingMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/handleInterface", Method: "Ping", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return handleInterface_client_stub{stub: stub, addMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/handleInterface", Method: "Add", Remote: true}), innerEchoMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/handleInterface", Method: "InnerEcho", Remote: true}), pingMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivian/pkg/server/handleInterface", Method: "Ping", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return handleInterface_server_stub{impl: impl.(handleInterface), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return handleInterface_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[weaver.Main] = (*Server)(nil)
var _ weaver.InstanceOf[handleInterface] = (*serverControls)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*Server)(nil)
var _ weaver.Unrouted = (*serverControls)(nil)

// Local stub implementations.

type main_local_stub struct {
	impl   weaver.Main
	tracer trace.Tracer
}

// Check that main_local_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_local_stub)(nil)

type handleInterface_local_stub struct {
	impl             handleInterface
	tracer           trace.Tracer
	addMetrics       *codegen.MethodMetrics
	innerEchoMetrics *codegen.MethodMetrics
	pingMetrics      *codegen.MethodMetrics
}

// Check that handleInterface_local_stub implements the handleInterface interface.
var _ handleInterface = (*handleInterface_local_stub)(nil)

func (s handleInterface_local_stub) Add(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	begin := s.addMetrics.Begin()
	defer func() { s.addMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "server.handleInterface.Add", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Add(ctx, a0)
}

func (s handleInterface_local_stub) InnerEcho(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	begin := s.innerEchoMetrics.Begin()
	defer func() { s.innerEchoMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "server.handleInterface.InnerEcho", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.InnerEcho(ctx, a0)
}

func (s handleInterface_local_stub) Ping(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	begin := s.pingMetrics.Begin()
	defer func() { s.pingMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "server.handleInterface.Ping", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Ping(ctx, a0)
}

// Client stub implementations.

type main_client_stub struct {
	stub codegen.Stub
}

// Check that main_client_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_client_stub)(nil)

type handleInterface_client_stub struct {
	stub             codegen.Stub
	addMetrics       *codegen.MethodMetrics
	innerEchoMetrics *codegen.MethodMetrics
	pingMetrics      *codegen.MethodMetrics
}

// Check that handleInterface_client_stub implements the handleInterface interface.
var _ handleInterface = (*handleInterface_client_stub)(nil)

func (s handleInterface_client_stub) Add(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.addMetrics.Begin()
	defer func() { s.addMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "server.handleInterface.Add", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.String()
	err = dec.Error()
	return
}

func (s handleInterface_client_stub) InnerEcho(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.innerEchoMetrics.Begin()
	defer func() { s.innerEchoMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "server.handleInterface.InnerEcho", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 1, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.String()
	err = dec.Error()
	return
}

func (s handleInterface_client_stub) Ping(ctx context.Context, a0 string) (r0 string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.pingMetrics.Begin()
	defer func() { s.pingMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "server.handleInterface.Ping", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.String()
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.22.0 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type main_server_stub struct {
	impl    weaver.Main
	addLoad func(key uint64, load float64)
}

// Check that main_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*main_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s main_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	default:
		return nil
	}
}

type handleInterface_server_stub struct {
	impl    handleInterface
	addLoad func(key uint64, load float64)
}

// Check that handleInterface_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*handleInterface_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s handleInterface_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "Add":
		return s.add
	case "InnerEcho":
		return s.innerEcho
	case "Ping":
		return s.ping
	default:
		return nil
	}
}

func (s handleInterface_server_stub) add(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Add(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.String(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s handleInterface_server_stub) innerEcho(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.InnerEcho(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.String(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s handleInterface_server_stub) ping(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.Ping(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.String(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type main_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that main_reflect_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_reflect_stub)(nil)

type handleInterface_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that handleInterface_reflect_stub implements the handleInterface interface.
var _ handleInterface = (*handleInterface_reflect_stub)(nil)

func (s handleInterface_reflect_stub) Add(ctx context.Context, a0 string) (r0 string, err error) {
	err = s.caller("Add", ctx, []any{a0}, []any{&r0})
	return
}

func (s handleInterface_reflect_stub) InnerEcho(ctx context.Context, a0 string) (r0 string, err error) {
	err = s.caller("InnerEcho", ctx, []any{a0}, []any{&r0})
	return
}

func (s handleInterface_reflect_stub) Ping(ctx context.Context, a0 string) (r0 string, err error) {
	err = s.caller("Ping", ctx, []any{a0}, []any{&r0})
	return
}
