// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package database

import (
	"context"
	"errors"
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:  "vivianlab/database/Database",
		Iface: reflect.TypeOf((*Database)(nil)).Elem(),
		Impl:  reflect.TypeOf(impl{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return database_local_stub{impl: impl.(Database), tracer: tracer, fetchAccountMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivianlab/database/Database", Method: "FetchAccount", Remote: false}), initMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivianlab/database/Database", Method: "Init", Remote: false})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return database_client_stub{stub: stub, fetchAccountMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivianlab/database/Database", Method: "FetchAccount", Remote: true}), initMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "vivianlab/database/Database", Method: "Init", Remote: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return database_server_stub{impl: impl.(Database), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return database_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[Database] = (*impl)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*impl)(nil)

// Local stub implementations.

type database_local_stub struct {
	impl                Database
	tracer              trace.Tracer
	fetchAccountMetrics *codegen.MethodMetrics
	initMetrics         *codegen.MethodMetrics
}

// Check that database_local_stub implements the Database interface.
var _ Database = (*database_local_stub)(nil)

func (s database_local_stub) FetchAccount(ctx context.Context, a0 string) (r0 Account, err error) {
	// Update metrics.
	begin := s.fetchAccountMetrics.Begin()
	defer func() { s.fetchAccountMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "database.Database.FetchAccount", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.FetchAccount(ctx, a0)
}

func (s database_local_stub) Init(ctx context.Context) (err error) {
	// Update metrics.
	begin := s.initMetrics.Begin()
	defer func() { s.initMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "database.Database.Init", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.Init(ctx)
}

// Client stub implementations.

type database_client_stub struct {
	stub                codegen.Stub
	fetchAccountMetrics *codegen.MethodMetrics
	initMetrics         *codegen.MethodMetrics
}

// Check that database_client_stub implements the Database interface.
var _ Database = (*database_client_stub)(nil)

func (s database_client_stub) FetchAccount(ctx context.Context, a0 string) (r0 Account, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.fetchAccountMetrics.Begin()
	defer func() { s.fetchAccountMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "database.Database.FetchAccount", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	(&r0).WeaverUnmarshal(dec)
	err = dec.Error()
	return
}

func (s database_client_stub) Init(ctx context.Context) (err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.initMetrics.Begin()
	defer func() { s.initMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "database.Database.Init", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 1, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.22.0 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type database_server_stub struct {
	impl    Database
	addLoad func(key uint64, load float64)
}

// Check that database_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*database_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s database_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "FetchAccount":
		return s.fetchAccount
	case "Init":
		return s.init
	default:
		return nil
	}
}

func (s database_server_stub) fetchAccount(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.FetchAccount(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	(r0).WeaverMarshal(enc)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s database_server_stub) init(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	appErr := s.impl.Init(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type database_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that database_reflect_stub implements the Database interface.
var _ Database = (*database_reflect_stub)(nil)

func (s database_reflect_stub) FetchAccount(ctx context.Context, a0 string) (r0 Account, err error) {
	err = s.caller("FetchAccount", ctx, []any{a0}, []any{&r0})
	return
}

func (s database_reflect_stub) Init(ctx context.Context) (err error) {
	err = s.caller("Init", ctx, []any{}, []any{})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Account)(nil)

type __is_Account[T ~struct {
	weaver.AutoMarshal
	ID       int
	Alias    string
	Name     string
	Email    string
	Password string
	Tier     int
}] struct{}

var _ __is_Account[Account]

func (x *Account) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Account.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.ID)
	enc.String(x.Alias)
	enc.String(x.Name)
	enc.String(x.Email)
	enc.String(x.Password)
	enc.Int(x.Tier)
}

func (x *Account) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Account.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.Int()
	x.Alias = dec.String()
	x.Name = dec.String()
	x.Email = dec.String()
	x.Password = dec.String()
	x.Tier = dec.Int()
}
