[vivian]
version = "alpha v2.0.1"

[serviceweaver]
binary = "vivian"

[single]
listeners.vivian = {address = "localhost:9000"}

[gke]
regions = ["us-east1"]
listeners.vivian = {public_hostname = "vivian.com"}

[database]
name = "vivian_users"
address = "127.0.0.1:3306"

