// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package models

import (
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
)

// weaver.InstanceOf checks.

// weaver.Router checks.

// Local stub implementations.

// Client stub implementations.

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][20]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.22.0 (codegen
version v0.20.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

// Reflect stub implementations.

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*Account)(nil)

type __is_Account[T ~struct {
	weaver.AutoMarshal
	ID       int
	Alias    string
	Name     string
	Email    string
	Password string
	Tier     int
}] struct{}

var _ __is_Account[Account]

func (x *Account) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Account.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.ID)
	enc.String(x.Alias)
	enc.String(x.Name)
	enc.String(x.Email)
	enc.String(x.Password)
	enc.Int(x.Tier)
}

func (x *Account) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Account.WeaverUnmarshal: nil receiver"))
	}
	x.ID = dec.Int()
	x.Alias = dec.String()
	x.Name = dec.String()
	x.Email = dec.String()
	x.Password = dec.String()
	x.Tier = dec.Int()
}
